config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/post/:id', to: 'posts#show', as: 'post'

  get '/data' => 'unsecured_pages#data'

  get '/roulette' => 'static_pages#roulette'
  get '/about' => 'static_pages#about'
  get '/submit' => 'posts#new'
 
  get '/browse' => 'posts#browse'
  post '/inc_spark_count/:id' => 'posts#inc_spark_count'

  get '/user' => 'users#user'
  get '/profile/:username' => 'users#other_user'
  post '/user_update' => 'users#update'

  get '/results' => 'roulettes#results'

  root 'users#user'
  

  resources :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :vibes
	has_many :comments
end

app/models/sparkey_post.rb
class SparkeyPost < ActiveRecord::Base
end

app/models/user.rb
 	class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :vibes
end

app/models/vibe.rb
class Vibe < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
	end

	def show
		@id = params[:id]
		@post = Post.find(@id)
		@post.views += 1
		@post.save
		# User inputted vibes
		vibes_string_list = params[:vibes]

		# Array of vibes that belong to current post
		@post_vibes = Vibe.where(:post_id => @id)

		@vibes_frequency_hash = Hash.new(0)
		@post_vibes.each {|vibe| @vibes_frequency_hash[vibe.vibe] += 1}


		if !vibes_string_list.nil?
			# Make an array of vibes
			vibes_string_list.chomp
			vibes_string_list.gsub(/\t/, '')
			vibes_string_list = vibes_string_list.gsub(" ", "")
			vibes_list = vibes_string_list.split(",")
			# Associate each vibe to current post
			vibes_list.each do |vibe|
				new_vibe = Vibe.new
				new_vibe.vibe = vibe
				new_vibe.post_id = @id
				new_vibe.save
			end
			redirect_to @post
		else
			render :template => 'posts/post'
		end
	end


	def browse
		results_list = Hash.new
		posts = Post.order(spark_count: :desc).limit(15)
		posts.each do |p|
			p_vibes = Vibe.where(:post_id => p.id)
			results_list[p] = p_vibes
		end

		@final_results_list = results_list
	end


	def create
	  @post = Post.new
	  @uploaded_io = params[:posts][:picture]

	  File.open(Rails.root.join('public', 'uploads', @uploaded_io.original_filename), 'wb') do |file|
	    file.write(@uploaded_io.read)
	  end
	  #render plain: @post
	  @post[:image_path] = "/../uploads/" + @uploaded_io.original_filename
	  @post[:spark_count] = 0
	  @post[:description] = params[:posts][:text] 
	  @post[:views] = 0
	  @post[:post_type] = params[:posts][:title]
	  @post[:user_id] = current_user[:id]
	  #@title = params[:posts][:title]
	  #@description = params[:posts][:text] 
	  @post.save
	  redirect_to '/post/' + @post[:id].to_s
	  #should have redirec to post/id#
	end

	def inc_spark_count
		post = Post.find(params[:id])
		post.spark_count += 1
		post.save
		redirect_to '/post/' + post[:id].to_s
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	  def sign_up_params
	    params.require(:user).permit(:username, :email, :password, :password_confirmation)
	  end
end

app/controllers/roulettes_controller.rb
class RoulettesController < ApplicationController
	
	def results

		# Creates an array of vibes 
		vibes_string_list = params[:vibes]
		vibes_string_list = vibes_string_list.chomp
		vibes_string_list = vibes_string_list.rstrip.lstrip
		vibes_string_list = vibes_string_list.gsub(" ", "")
		vibes_list = vibes_string_list.split(",")

		# Depending on if user entered vibes, return results
		# 	1. If there are one or more vibes, do vibes_search
		# 	2. Else, do default search
		num_posts = 10
		legit_vibes = []
		results_list = Hash.new
		vibes_list.each do |vibe|
			legit_vibes += Vibe.where(:vibe => vibe)
		end
		post = []
		if(vibes_list.size == 1)
			legit_vibes.each do |vibe|
				post += Post.where(:id => vibe.post_id)
			end
			#post = Post.where(:id => legit_vibes[0].post_id)
		elsif(vibes_list.size > 1)
			legit_vibes.each do |vibe|
				post += Post.where(:id => vibe.post_id)
			end
		else		
			post = Post.order(views: :asc, created_at: :asc).limit(num_posts)
		end

		post.each do |p|
			p_vibes = Vibe.where(:post_id => p.id)
			results_list[p] = p_vibes
		end

		@final_results_list = results_list
		@roulette = true

		render :template => 'posts/browse'
		
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
	def roulette

	end

	def submit

	end

end

app/controllers/unsecured_pages_controller.rb
class UnsecuredPagesController 
	def splash

	end

	def data
		@posts = Post.all
		@comments = Comment.all
		@vibes = Vibe.all
		@users = User.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def user
		@user = current_user;
		posts = Post.where(:user_id => @user.id)
		@vibes_frequency_hash = Hash.new(0)
		posts.each do |p|
			post_vibes = Vibe.where(:post_id => p.id)
			post_vibes.each {|vibe| @vibes_frequency_hash[vibe.vibe] += 1}
		end
	end

	def other_user
		username = params.require(:username)
		@user = User.find_by username: username;
		posts = Post.where(:user_id => @user.id)
		@vibes_frequency_hash = Hash.new(0)
		posts.each do |p|
			post_vibes = Vibe.where(:post_id => p.id)
			post_vibes.each {|vibe| @vibes_frequency_hash[vibe.vibe] += 1}
		end
		render :template => 'users/user'
	end

	def update
		begin
			@uploaded_io = params[:user][:picture]
	    	to_array = @uploaded_io.original_filename.lines(".")
	    	result_array = []
	    	to_array.each { |x| result_array.push(x) }
			if result_array[1] == "png"
				File.open(Rails.root.join('public', 'profilepictures', current_user[:username] + ".png"), 'wb') do |file|
		    		file.write(@uploaded_io.read)
		    	end
		    end
		rescue
		end

		begin 
			@status = params[:user][:about]
			current_user[:about] = @status
			current_user.save
			#render plain: current_user[:about]
		rescue
		end
		redirect_to "/"
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/roulette_configs_helper.rb
module RouletteConfigsHelper
end

app/helpers/roulette_searches_helper.rb
module RouletteSearchesHelper
end

app/helpers/roulettes_helper.rb
module RoulettesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/unsecured_pages_helper.rb
module UnsecuredPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/browse.html.erb
<% if @roulette %>
    <% provide(:title, "Roulette") %>
    <% provide(:selected, ["roulette"]) %>
<% else %>
    <% provide(:title, "Browse") %>
    <% provide(:selected, ["browse"]) %>
<% end %>

<% content_for :head do %>
<% end %>

<style>
    .col-md-6 {
        margin: auto;
        text-align: center;
    }
</style>



<div class="container">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <h3 class="big-text black">
                <% if @roulette %>
                    Roulette Results
                <% else %>
                    Popular
                <% end %>
            </h3>
            <% @final_results_list.each do |post, vibes| %>
            <div class="browse-item">
                <%= link_to posts_path + "/" + post[:id].to_s do %>
                    <%= image_tag(post.image_path) %>
                    <% if (vibes.size - 1) < 2 %> 
                        <% iterate_to = (vibes.size - 1) %>
                    <% else %>
                        <% iterate_to = 2 %>
                    <% end %>
                    <div class="item-info">
                        <table class="item-table">
                            <tr>
                                <td class="icon"><span class="glyphicon glyphicon-picture"></span></td>
                               
                                    <% for i in 0..iterate_to %>
                                        <td><%= vibes[i][:vibe] %></td>
                                    <%  end %>
                            </tr>
                        </table>
                    </div>
                <% end %> 
            </div>
            <% end %>
        </div>
        <div class="col-md-3">
        </div>
    </div>
</div>

app/views/posts/create.html.erb
<% provide(:title, @uploaded_io.original_filename) %>
<% provide(:selected, []) %>
<% content_for :head do %>
    <%= javascript_include_tag "search.js" %>
<% end %>
<style>
.col-md-5 {
    float: none;
    margin: 0 auto;
    text-align: center;
}
.col-md-5 div {
    width: 100%;
}
#roulette-box {
    border-top: none;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
#image-box img {
	width: 100%;
}
</style>
<div class="container">
    <div class="clearer">&nbsp;</div>
    <div class="row">
        <div class="col-md-5">
            <h3>
                <%= @title %>
            </h3>
            <div id="image-box">
                <%= image_tag "/uploads/#{@uploaded_io.original_filename}" %>
            </div>
            <div class="clearer">&nbsp;</div>
            <div class="desc-box black">
                <p>
                    <%= @description %>
                </p>
            </div>
            <div class="clearer">&nbsp;</div>
            <p>
                Give it a 
                <input type="submit" value="Spark!">
                
            </p>
                <div class="clearer">&nbsp;</div>
            <div id="vibe-tab" class="tab">Vibes</div>
            <div id="comment-tab" class="tab unselected">Comments</div>
            <div class="clearer"></div>
            <div class="form-container" id="roulette-box">
                <div class="clearer">&nbsp;</div>
                <div class="clearer">&nbsp;</div>
                <div id="vibe-box">
                    <img src="./images/placeholder_roulette.png"/>
                    <div class="clearer">&nbsp;</div>
                    <form>
                        <textarea class="long" placeholder="Enter vibes"></textarea>
                        <div class="clearer">&nbsp;</div>
                        <input type="submit" value='Submit'/>
                        <div class="clearer">&nbsp;</div>
                    </form>
                </div>
                <div id="comment-box" class="hidden">
                    <form>
                        <textarea class="long" placeholder="Enter a comment"></textarea>
                        <div class="clearer">&nbsp;</div>
                        <input type="submit" value='Submit'/>
                        <div class="clearer">&nbsp;</div>
                    </form>
                    <ul id="comments">
                        <li class="comment">
                            <a class="red-link" href="./~profile-vvvvvvitellary.html">
                                <h4>
                                    vvvvvvitellary
                                </h4>
                            </a>
                            <p>
                                Should have stayed away from the pinkish hues on the hilt and handle - makes it look more like a strawberry than a flaming sword.
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="clearer">&nbsp;</div>
            <div class="clearer">&nbsp;</div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Submit") %>
<% provide(:selected, ["submit"]) %>
<% content_for :head do %>
<% end %>


<style>
    .col-md-5 {
        float: none;
        margin: 0 auto;
    }
    input[type=file]::before {
        content: "Drag a file in here or";
        top: 4rem;
        left: 0;
        right: 0;
        text-align: center;
        position: absolute;
    }
    input[type=file] {
        padding-left: 15%;
        height: auto;
        padding-bottom: 6rem;
    }
</style>
    <div class="container">
        <div class="clearer">&nbsp;</div>
        <div class="row">
            <div class="col-md-5">
                <div class="form-container">
                    <h3>
                        Submit
                    </h3>
                    <%= form_for :posts, url: posts_path do |f| %>
                    <p>
                        <%= f.text_field :title, :placeholder => 'title', :required => 'required' %>
                    </p>
                    <p>
                        <%= f.file_field :picture, :required => 'required'%>
                    </p>
                    <p>
                        <%= f.text_area :text, :placeholder => 'Write a description...' %>
                    </p>

                    <p>
                    <%= f.submit "Submit" %>
                    </p>
                <% end %>
                </div>
            </div>
            <div class="col-md-3">
            </div>
        </div>
        <div class="clearer">&nbsp;</div>
    </div>

app/views/posts/post.html.erb
<% provide(:title, @post[:post_type].to_s) %>
<% provide(:selected, []) %>
<% content_for :head do %>
    <%= javascript_include_tag "search.js" %>
    <%= javascript_include_tag "generate_word_cloud" %>
<% end %>

<style>
    .col-md-5 {
        float: none;
        margin: 0 auto;
        text-align: center;
    }
    .col-md-5 div {
        width: 100%;
    }
    #roulette-box {
        border-top: none;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
    #cloud {
        margin-bottom: 2rem;
        height: 15rem;
        width: 35rem;
    }
</style>
<script>
    var words = [
        <% @vibes_frequency_hash.each do |key, array| %>
            <% word = key.dup %>
            {text: "<%= word.rstrip.lstrip %>", weight: "<%= array %>"},
        <% end %>
    ]
</script>
<div class="container">
    <div class="clearer">&nbsp;</div>
    <div class="row">
        <div class="col-md-5">
            <h3>
                <%= @post[:post_type] %>
            </h3>
            <div id="image-box">
                <%= image_tag("#{@post[:image_path]}", :id => "roulette-image") %>
            </div>
            <div class="clearer">&nbsp;</div>
            <div class="desc-box black">
                <p>
                    <%= @post[:description] %>
                </p>
            </div>
            <div class="clearer">&nbsp;</div>
            <p>
                Give it a 
                <%= form_tag({controller: "posts", action: "inc_spark_count"}, method: "post") do %>
                    <%= hidden_field_tag :id , @post[:id] %>
                    <%= submit_tag("Spark!") %>
                <% end %>
            </p>
                <div class="clearer">&nbsp;</div>
            <div id="vibe-tab" class="tab">Vibes</div>
            <div id="comment-tab" class="tab unselected hidden">Comments</div>
            <div class="clearer"></div>
            <div class="form-container" id="roulette-box">
                <div class="clearer">&nbsp;</div>
                <div class="clearer">&nbsp;</div>
                <div id="vibe-box" class="">
                    <div id="cloud">
                    </div>
                    <%= form_tag({controller: "posts", action: "show"}, method: "get") do %>
                        <%= text_area_tag(:vibes, "", size: "24x6", :placeholder => "Enter vibes seperated by commas...", :class => "long") %>
                        <div class="clearer">&nbsp;</div>
                        <%= submit_tag("Submit!") %>
                    <% end %>
                    <div class="clearer">&nbsp;</div>
                </div>
                <div id="comment-box" class="hidden">
                    <form>
                        <textarea class="long" placeholder="Enter a comment"></textarea>
                        <div class="clearer">&nbsp;</div>
                        <input type="submit" value='Submit'/>
                        <div class="clearer">&nbsp;</div>
                    </form>
                    <ul id="comments">
                        <li class="comment">
                            <a class="red-link">
                                <h4>
                                    Anonymous
                                </h4>
                            </a>
                            <p>
                                CommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentComment
                            </p>
                        </li>
                        <li class="comment">
                            <a class="red-link">
                                <h4>
                                    Anonymous
                                </h4>
                            </a>
                            <p>
                                CommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentCommentComment
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="clearer">&nbsp;</div>
            <div class="clearer">&nbsp;</div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container">
    <div class="clearer">&nbsp;</div>
    <div class="row">
        <div class="col-md-5">
            <div class="form-container">
                <h3>
                    Vibes
                </h3>
              
                <%= form_tag({controller: "posts", action: "show"}, method: "get") do %>
                    <%= text_area_tag(:vibes, "", size: "24x6", :placeholder => "Enter vibes...") %>
                    <%= submit_tag("Go!") %>
                <% end %>
            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
    <div class="clearer">&nbsp;</div>
</div>

app/views/users/user.html.erb
<% provide(:title, "Profile") %>
<% provide(:selected, []) %>
<% content_for :head do %>
	<%= stylesheet_link_tag "profile.css" %>
	<%= javascript_include_tag "generate_word_cloud" %>
<% end %>

<script>
    var words = [
        <% @vibes_frequency_hash.each do |key, array| %>
            <% word = key.dup %>
            {text: "<%= word.rstrip.lstrip %>", weight: "<%= array %>"},
        <% end %>
    ]
</script>
<div class="container">
    <div id="profile">
		<div id="leftpage" class="page">
			<%= image_tag("leftPage.png", :alt => "leftPage", :class => "pageimage") %>
			<div id="leftpagetext" class="pagetext">
			<%= image_tag("/profilepictures/#{@user[:username]}.png", :alt => "Upload a profile pic!", :id => "profilepic") %>
				<p class="pagetitle"> <%= @user.username %></p>
				<p id="status"><%= @user.about %></p>
		<% if current_user[:id] == @user[:id] %>
			<%= form_for :user, url: user_update_path do |f| %>
				<p id="profilePic">
					<%= f.file_field :picture %>
				</p>
				<p>
					<%= f.text_field :about, :placeholder => 'Update your status:' %>
				</p>

				<p>
				<%= f.submit "Submit" %>
				</p>
			<% end %>
		<% end %>
					</div>
		</div>
		<div id="rightpage" class="page">
			<%= image_tag("rightPage.png", :alt => "rightPage", :class => "pageimage") %>
			<div id="vibes" class="pagetext">
				<p class="pagetitle">Vibes</p>
				<div id="cloud">
				</div>
			</div>
		</div>
	</div>
</div>